-- Filename: setup_oracle_environment.sql

-- 1. Create Tablespace
CREATE TABLESPACE stbl_tablespace
DATAFILE 'stbl_tablespace.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL;

-- 2. Create User
CREATE USER stbl_user IDENTIFIED BY stbl_password
DEFAULT TABLESPACE stbl_tablespace
QUOTA UNLIMITED ON stbl_tablespace;

-- 3. Grant Privileges
GRANT CONNECT, RESOURCE TO stbl_user;

-- 4. Create Table
CONNECT stbl_user/stbl_password;

CREATE TABLE stbl_table (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(50),
    age NUMBER,
    join_date DATE
);

-- 5. Insert Sample Data
INSERT INTO stbl_table (name, age, join_date) VALUES ('Anas_Bhai', 33, SYSDATE);
INSERT INTO stbl_table (name, age, join_date) VALUES ('Niaz_bhai', 28, SYSDATE);
INSERT INTO stbl_table (name, age, join_date) VALUES ('Oni_bhai', 25, SYSDATE);
COMMIT;

-- 6. Verification Commands
-- Check Current User
SELECT USER FROM DUAL;

-- Check Current Container (if using CDB)
SELECT NAME FROM V$DATABASE;

-- List All Schemas
SELECT USERNAME FROM DBA_USERS ORDER BY USERNAME;

-- List All Tables in the Database
SELECT TABLE_NAME FROM ALL_TABLES;

-- Verify Tablespace
SELECT TABLESPACE_NAME, STATUS FROM DBA_TABLESPACES WHERE TABLESPACE_NAME = 'STBL_TABLESPACE';

-- Verify User
SELECT USERNAME, ACCOUNT_STATUS FROM DBA_USERS WHERE USERNAME = 'STBL_USER';

-- Verify Tables
SELECT TABLE_NAME FROM ALL_TABLES WHERE OWNER = 'STBL_USER';

-- Verify Data
SELECT * FROM stbl_table;

-- Remove Section (Uncomment to execute)
-- Note: Use with caution! This will remove all created objects.

-- 7. Drop the Table
-- CONNECT stbl_user/stbl_password;
-- DROP TABLE stbl_table;

-- 8. Drop the User
-- CONNECT sys as sysdba;
-- DROP USER stbl_user CASCADE;

-- 9. Drop the Tablespace
-- DROP TABLESPACE stbl_tablespace INCLUDING CONTENTS AND DATAFILES;

-- End of script
